version: 1
blueprint: container_fargate
app_slug: caller-id
stage: dev
container:
  dockerfile: Dockerfile
  context: .
  port: 8000
  health_check_path: /health
  cpu: 512
  memory: 1024
  desired_count: 1
features:
  redis: true
databases:
  rds:
    enabled: true
    engine: postgres
    instance_class: db.t3.micro
    storage_gb: 20
    db_name: caller_id_db
    username: appuser
    password: autodeploy-ydEGM89G5Ec
secrets:
  _import_env: true
  _env_file: .env
  _deny:
  - REDIS_URL
  - POSTGRES_HOST
  - POSTGRES_PORT
  - POSTGRES_DB
  - POSTGRES_USER
  - POSTGRES_PASSWORD
